include:
  - project: 'devops/gitlab-ci'
    ref: master
    file: '/snippets/.defaults.yaml'
  - project: 'devops/gitlab-ci'
    ref: master
    file: '/snippets/.poetry-env.yaml'
  - project: 'devops/gitlab-ci'
    ref: master
    file: '/snippets/.acceptance-verify-commit-message.yaml'

stages:
  - acceptance
  - build
  - deploy

.poetry-config:
  before_script:
    - poetry config repositories.igenius ${POETRY_GROUP_REPOSITORY}
    - poetry config http-basic.igenius ${POETRY_AUTH}

compile-docs:
  image: $CI_REGISTRY/utilities/igenius.ci-docker-images-backend:python-3.7
  stage: build
  artifacts:
    expire_in: "1h"
    paths:
      - site/
  script:
    - pip install -r docs/ci-requirements.txt
    - mkdocs build
  only:
    - tags

publish-pypi:
  image: $CI_REGISTRY/utilities/igenius.ci-docker-images-backend:python-3.8
  stage: deploy
  script:
    - pip install poetry
    - poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
  only:
    - tags
