include:
  - project: 'devops/gitlab-ci'
    ref: master
    file: '/snippets/.defaults.yaml'
  - project: 'devops/gitlab-ci'
    ref: master
    file: '/snippets/.poetry-env.yaml'
  # - project: 'devops/gitlab-ci'
  #   ref: master
  #   file: '/snippets/.build-push.yaml'

stages:
  - build
  - deploy
  - build-push

compile-docs:
  image: $CI_REGISTRY/utilities/igenius.ci-docker-images-backend:python-3.7
  stage: build
  artifacts:
    expire_in: "1h"
    paths:
      - site/
  script:
    - pip install -r docs/ci-requirements.txt
    - mkdocs build

# .deploy-docs:
#   variables:
#     DOCS_BUCKET_NAME: 'static-demo.crystal.ai'
#     DOCS_BUCKET_PREFIX: 'libraries/igenius-adapters-sdk'
#   image:
#     name: mesosphere/aws-cli:1.14.5
#     entrypoint:
#       - "sh"
#       - "-c"
#   dependencies:
#     - compile-docs
#   script:
#     - aws s3 sync --acl public-read ./site/ "s3://${DOCS_BUCKET_NAME}/${DOCS_BUCKET_PREFIX}/${DOCS_VERSION}/"
#   except:
#     - schedules

# deploy-docs-latest:
#   stage: deploy
#   extends: .deploy-docs
#   variables:
#     DOCS_VERSION: 'latest'
#   # only:
#   #   - master

# deploy-docs-tagged:
#   stage: deploy
#   extends: .deploy-docs
#   variables:
#     DOCS_VERSION: $CI_COMMIT_TAG
#   only:
#     - tags