site_name: iGenius Adapters SDK
nav:
  - Home: index.md
  - Entities:
    - Collection: entities/collection.md
    - URIs: entities/uri.md
    - Data Attributes: entities/data_attributes.md
    - Numeric Binnings: entities/numeric_binnings.md
    - Parameters: entities/parameters.md
    - Aggregation Functions: entities/aggregation_functions.md
    - GroupBy Functions: entities/groupby_functions.md
    - Joins: entities/joins.md
    - Expressions: entities/expressions.md
    - Queries: entities/queries.md
    - i18n Translations: entities/i18n_translations.md
    - Errors: entities/errors.md
  - Query examples:
      - Aggregation with static values: query_examples/aggregation_with_static_values.md
      - Join projection: query_examples/join_projection.md
      - Order by: query_examples/order_by.md
      - Distinct: query_examples/distinct.md
      - Select all: query_examples/select_all.md
      - Where: query_examples/where.md

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Purple'
    accent: 'Light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true